#+TITLE: 6.11.2019
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css" />
#+HTML_HEAD: <style>div.figure img {max-height:300px;max-width:900px;}</style>
#+HTML_HEAD_EXTRA: <style>.org-src-container {background-color: #303030; color: #e5e5e5;}</style>

* Конфиг emacs
  Конфигурация emacs лежит в файле: =~/.emacs=.

  #+INCLUDE: ~/.emacs src elisp

* [[https://orgmode.org/][org mode]]
  Что почитать:
  1. [[https://habr.com/ru/post/105300/][Введение в org-mode emacs на habr]]

* Dat protocol, или как обмениваться файлами без облаков.
** Что это такое
   У вас много файликов на компе и надо пошарить директорию среди
   друзей без третьей стороны. 

** Какие есть решения?
   1. ftp сервер и web сервер
   2. облачные хранилища _вот так нельзя!_
   3. torrent - хороший инструмент, но в нем нет возможности
      синхронизовывать обновления директории
   4. dat протокол

** Установка dat через npm
   Так обычно делают javascript программисты

*** DONE Нужен nodejs
    У обладателей NixOS он уже стоит
*** DONE нужен npm - менеджер пакетов
    nodejs тянет за собой npm.
*** DONE Настройка npm
    Надо сделать так, чтобы npm ставил программы в определенную
    директорию.

    Для этого надо отредактировать файлик: =~/.npmrc=
    #+BEGIN_SRC sh
    prefix = ${HOME}/.npm-packages
    #+END_SRC

*** Ставим dat командой
    #+BEGIN_SRC sh
      npm install -g dat
    #+END_SRC

** Используем dat
   Сценарий: один желает делиться контентом некой директории =foo=,
   остальные желают иметь свежую версию этого контента.
*** Желающий поделиться
    Идет в директорию =foo= и запускает там =dat=
    #+BEGIN_SRC sh
      cd foo
      ~/.npm-packages/bin/dat share 
    #+END_SRC

    После запуска =dat= сгенерирует ссылку, по которой будет доступен
    =foo=.
*** Желающий получить =foo= на своей машине выполняет
    #+BEGIN_SRC sh
      ~/.npm-packages/bin/dat clone <dat ссылка> foo
    #+END_SRC

    Возможно =dat clone= не с первого раза найдет информацию по dat
    ссылке.

    После удачного клонирования в директорию =foo= вы можете выбрать
    роль раздающего этот контент.Для этого надо перейти в =foo= и
    запустить там =dat sync=:

    #+BEGIN_SRC sh
      cd foo
      ~/.npm-packages/bin/dat sync
    #+END_SRC

* Экспортируем org файл в html
   Для экспорта надо набрать в emacs сочетание клавиш: =C-c-e h h=.

* Git
** Что почитать
   1. [[https://git-scm.com/book/ru/v2][git book]]

* Подвал
** Был вопрос про =BEGIN_SRC=
  #+BEGIN_SRC python
    def f(x):
	return x*x

    for i in range(100):
	v = f(i)
	print(v)
  #+END_SRC

  #+BEGIN_SRC elisp
    (+ 2 3 4)
  #+END_SRC

  #+BEGIN_SRC c
    int main () {
      char *str = "Hello world";
      printf("%s", str);
      return 0;
    }
  #+END_SRC
** TODO Надо подключить таблицу стилей.
** TODO работа в tmux
   1. [[https://habr.com/ru/post/126996/][Краткая шпаргалка по tmux (менеджеру терминалов)]] - статья на Хабре

*** Часто используемые сочетания клавиш
    - C-b c :: создать окно
    - C-b n :: переключиться на следующее окно
    - C-b d :: отсоединиться от tmux
    - =tmux attach= :: присоединиться к сессии tmux
    - C-b s :: выбор сессии tmux
